services:
  postgres:
    container_name: postgres-studplatform
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "stud_platform"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z.fips
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

volumes:
  postgres-data:
  minio_data:
