"""initial3

Revision ID: 7a9789fa2260
Revises: aee6dd5eca1e
Create Date: 2025-01-03 01:45:25.022925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9789fa2260'
down_revision: Union[str, None] = 'aee6dd5eca1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', 'description')
    # ### end Alembic commands ###
